### ISSUE TITLE
colour.js file is missing

### ISSUE THREAD

**Issue by CSASystems** [sujitrp/OPenHab-WLED-configuration-#1]
Hello,
everything is working just fine, but not the color pick as the colour.js is missing from your files package.

another thing to notice is that you need to add astrok 
you have it as 
[broker:wled/godlight2/api:command::MAP(wledColoreffectsJSON.map)]"}
it should be 
[broker:wled/godlight2/api:command:*:MAP(wledColoreffectsJSON.map)]"}

that should be applied on all the lines

**Comment by sujitrp** [comment]
Thanks CSASystems  updated color.js
