### ISSUE TITLE
Need Help to adapt it to mqtt2.4

### ISSUE THREAD

**Issue by ghost** [sujitrp/OPenHab-WLED-configuration-#2]
Hi !
thanks a lot for making it easy for everyone in the OH community.
Can you please suggest changes in the items to make it useful with a separate things file as in mqtt2.4.
Thanks

**Comment by thedannymullen** [comment]
I will be looking into this for my setup as I use wled and mqtt 2.x

I will post when complete be a week to 10days.

**Comment by ghost** [comment]
Hi though I got it to work with the below configuration but later found out that there is some problem with the wled release 8.6 because it is a pre release as of now. Hope they release a new version soon.
Things Definition

Thing mqtt:topic:ledStripThingId  "LED Strip"
     (mqtt:broker:brokerThingId) @ "My Room"
{
    Channels:
        Type switch : ledStrip "LED Strip" [ stateTopic="wled/740dd6/g", commandTopic="wled/740dd6", transformationPattern="MAP:LEDONOFF.map" ]
        Type dimmer : ledStripDimmerOne "Bed Room Night Brightness [%d]" [ stateTopic="wled/740dd6/g", commandTopic="wled/740dd6", min=0,max=255 ]
        Type dimmer : ledStripSpeedOne "Bed Room Night light Speed [%.0f]" [ stateTopic="wled/740dd6/api", commandTopic="wled/740dd6/api", min=0,max=255, formatBeforePublish="&SX=%s"  ]
        Type dimmer : ledStripIntensityOne "Bed Room Night light intensity [%.0f]" [ stateTopic="wled/740dd6/api", commandTopic="wled/740dd6/api", min=0,max=255, formatBeforePublish="&IX=%s" ]
        Type number : ledStripColorN "Bed Room Night Color" [  commandTopic="wled/740dd6/col", transformationPatternOut="MAP:wledColoreffectsJSON.map" ]
        Type number : ledStripEffects "Bed Room Night Effects" [ commandTopic="wled/740dd6/api", transformationPatternOut="MAP:wledColoreffectsJSON.map" ]
        Type number : ledStripPalettes "Bed Room Night Palettes" [ commandTopic="wled/740dd6/api", transformationPatternOut="MAP:wledColoreffectsJSON.map" ]
}

Item Definition

Switch LEDStrip  "LED Strip" ["Switchable"] { channel="mqtt:topic:ledStripThingId:ledStrip" }
Dimmer LEDStripDimmerOne  "Bed Room Night Brightness [%d]" { channel="mqtt:topic:ledStripThingId:ledStripDimmerOne" }
Dimmer LEDStripSpeedOne  "Bed Room Night light Speed [%.0f]" { channel="mqtt:topic:ledStripThingId:ledStripSpeedOne" }
Dimmer LEDStripIntensityOne  "Bed Room Night light intensity [%.0f]" { channel="mqtt:topic:ledStripThingId:ledStripIntensityOne" }
Number LEDStripColorN  "Bed Room Night Color" { channel="mqtt:topic:ledStripThingId:ledStripColorN" }
Number LEDStripEffects  "Bed Room Night Effects" { channel="mqtt:topic:ledStripThingId:ledStripEffects" }
Number LEDStripPalettes  "Bed Room Night Palettes" { channel="mqtt:topic:ledStripThingId:ledStripPalettes" }
Color LEDStripColor "Bed Room Night Color"

Rule for the Color Picker Item

rule "Publish changes to the Color for LEDs"
when
    Item LEDStripColor received update
then
         val HSBType newState = triggeringItem.state
         val rgb = 16777215 + newState.getRGB
         val mqttActions = getActions("mqtt","mqtt:broker:brokerThingId")           // use the Thing ID for your configured Broker
         mqttActions.publishMQTT("wled/740dd6/col",""+rgb)
end

Works now.
Sitemap remains the same, just edit the names accordingly.

**Comment by ghost** [comment]
Note: I did not use the js transformation as I read some OH developer somewhere saying on the forum that running JS engine inside takes great resources on the machine. Hence I went for simpler approach instead. Thanks
